### ISSUE TITLE
Git tagging and git cliff

### ISSUE THREAD

**Issue by iPromKnight** [knightcrawler-stremio/knightcrawler#118]
One of the tasks we need to do is to implement git tags on the repo, so we can maintain a changelog with [git cliff](https://git-cliff.org/).

This will help us keep track of the changes and features we add to our project.

 To do this, we will need to update our existing workflows to utilise tags, including these in docker container tags too.

This way, we can ensure that our docker images are consistent with our git versions. We will also set up a github action that fires at the same time as builds, and updates the changelog from the commits. This will automate the process and save us time and effort.

Everything should be tagged - even pre-release (alpha) merges into main, then cliff will maintain the full changelog.

**Comment by purple-emily** [comment]
I think this should be a high priority.
