### ISSUE TITLE
No really a bug report 

### ISSUE THREAD

**Issue by eoghan2t9** [knightcrawler-stremio/knightcrawler#154]
Hi all

I'm looking for some clarity of the way this whole process works. I have all the containers setup and they are all running. I can see the producer running through all the sites grabbing what it can however the consumers don't seem to be doing anything. I have tested my end point in stremio and also used the prowler torrentio yml and changed the address to my end point and it's not even finding anything.

Could someone please describe the steps that this going through?

Thanks

**Comment by purple-emily** [comment]
This is much easier to explain in live chat discord context

**Comment by eoghan2t9** [comment]
No worries I'll join the discord now ;)

**Comment by eoghan2t9** [comment]
Found support via discord
